services:
  application:
    image: learning_elixir:0.0.1
    container_name: learning_elixir
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/learning_elixir_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14-bullseye
    container_name: learning_elixir-postgres
    environment:
      - POSTGRES_DB=learning_elixir_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - learning_elixir_psql:/var/lib/postgresql/data
volumes:
  learning_elixir_psql:
